Tips page
CS633SP23Team4/magic-kitchen pull request #15
Opened 2024-02-18 15:31 UTC by T0ny-X

![image](https://github.com/CS633SP23Team4/magic-kitchen/assets/90066764/2ea39c0d-aad7-4d40-bce5-b64f75538175)
![image](https://github.com/CS633SP23Team4/magic-kitchen/assets/90066764/035f755c-29d0-4f7f-8616-8ef930a6c545)

2024-02-18 15:34 UTC, T0ny-X commented
https://magic-kitchen-b5f37--pr15-tips-page-1oad9e96.web.app/tips

2024-02-18 17:07 UTC, hetd54 requested changes

2024-02-18 17:07 UTC, hetd54 commented on src/routes/tips.jsx
> +                <Box display="grid" gridGap="4" gridTemplateColumns="repeat(auto-fit, minmax(300px, 1fr))">
can we center cards on mobile?

2024-02-19 01:51 UTC, AD121390 approved these changes
Looks great. My only nit pick is that the main title is the only clickable link. It would be nice if the entire card or picture was also a clickable link, but not a big deal.

2024-02-19 02:06 UTC, hetd54 approved these changes
Amazing 🚀

2024-02-19 03:14 UTC, merged